### ISSUE TITLE
Adding another harp.gl package

### ISSUE THREAD

**Issue by am2222** [slaylines/harp.gl-react-example#13]
Hello,
I wanted to use https://github.com/heremaps/harp-terrain-datasource package as well, Do I need to compile it with webpack too?

**Comment by mkalygin** [comment]
@am2222 I don't think so. It's just another dependency which you install with npm/yarn and use.

```bash
yarn add @here/harp-terrain-datasource
```

And in your code:

```js
import { TerrainDataSource } from '@here/harp-terrain-datasource';
```

**Comment by am2222** [comment]
@mkalygin thanks
