### ISSUE TITLE
webbox gl expression not evaluating

### ISSUE THREAD

**Issue by engdevlab** [slaylines/harp.gl-react-example#2]
This seems to be a react issue in evaluating mapbox expressions?   For the following, the when expression evaluations since changing the greater limit modifies the style appropriately.  But, the size expression with "get" never evaluates.  But, if I put an integer in size it evaluates fine.  Thoughts?

```
const styleSet = [
  {
    when: ["all", [">", ["get","busy_rank"], '70']],
    technique: 'circles',
    attr: {
      color: '#01a39c',
      size: ["get","busy_rank"],
      opacity: 0.5,
      renderOrder: 100,
    }
  }
];

```

**Comment by mkalygin** [comment]
Hi @engdevlab! I don't think it's related to React, because this `styleSet` is used with harp.gl methods, hence the expression you've mentioned is handled by harp.gl, not React.

**Comment by ninok** [comment]
@engdevlab What harp.gl version are you using? Can you try if this works with the latest harp (i.e. 0.13.1)?

**Comment by mkalygin** [comment]
@engdevlab @ninok I updated this example to use harp.gl v0.16.0. I hope it is solved now.
