### ISSUE TITLE
Map not rendering

### ISSUE THREAD

**Issue by gsavvid** [slaylines/harp.gl-react-example#4]
Hi, thanks for this sample project. Although the offices load fine, the map doesn't. I tried replacing your access token with mine in case yours expired but the result was the same. Here's a screenshot of the outcome. Any ideas what the issue might be?
<img width="1680" alt="Screenshot 2020-06-18 at 12 40 40" src="https://user-images.githubusercontent.com/5520133/85011092-5be68700-b161-11ea-88e8-2990a34ae354.png">

**Comment by mkalygin** [comment]
Hi @gsavvid! Thanks for the info. I've updated the code, now it should work fine. It was using latest version of a theme API, which is not compatible anymore with the version of a library in this repo.

**Comment by mkalygin** [comment]
@gsavvid Harp.gl version in this repo wasn't compatible with the `https://unpkg.com/@here/harp-map-theme` version (the latest was used, while harp.gl in this repo works with v0.10).

**Comment by gsavvid** [comment]
@mkalygin Are there any plans to update all harp.gl dependencies to the latest version (v0.16.0) perhaps?

**Comment by mkalygin** [comment]
@gsavvid I've updated the `master` branch. It works with the latest harp.gl v0.16.0 now.

**Comment by frobones** [comment]
@mkalygin Any plans to update all harp.gl dependencies to the latest version (v0.21.1)?

I've attempted myself, but the map doesn't render. I'm also new to web dev so there have been some learnign hurdles along the way.

**Comment by nzjony** [comment]
@frobones I did this yesterday in another repo, see: https://github.com/sainap/harpgl-samples/pull/2

**Comment by mkalygin** [comment]
@frobones I'll check this out and update the dependencies this weekend.

**Comment by frobones** [comment]
> @frobones I did this yesterday in another repo, see: [sainap/harpgl-samples#2](https://github.com/sainap/harpgl-samples/pull/2)
> 
> our check out: https://github.com/PanetoneCake/HarpGL-React.JS

Awesome, thank you for this!
