### ISSUE TITLE
Significant performance drop when using built app

### ISSUE THREAD

**Issue by harrycollin** [slaylines/harp.gl-react-example#6]
I've noticed after building the app there are huge performance problems. I initially noticed this on my own app but came back here as I used this as an initial reference a long time ago. It appears to have happened since upgrading from harp 0.14.0. What do you think is going wrong?

**Comment by nzjony** [comment]
I can reproduce this when running `yarn build` and serving the directory.

**Comment by mkalygin** [comment]
@harrycollin do you think it's related to React in any way? Do you experience slow build times using `harp.gl` without React?

**Comment by harrycollin** [comment]
@mkalygin I believe it's related [this ](https://github.com/heremaps/harp.gl/issues/1815#issuecomment-689466278). The guys at Here think it's because react-scripts transpiles to es5. Check [here](https://github.com/heremaps/harp.gl/issues/1815#issuecomment-689030589)

**Comment by mkalygin** [comment]
@harrycollin ok, this makes sense. Does the browserlist fix help? If so, I think I can include it in this example repo to fix the build performance issue.

**Comment by harrycollin** [comment]
@harrycollin I've only done an initial test and it does appear to work. Hopefully this is the solution!

**Comment by mkalygin** [comment]
Ok, I'm specifically linking the solution [here](https://github.com/heremaps/harp.gl/issues/1815#issuecomment-689466278) for future reference.

**Comment by mkalygin** [comment]
@harrycollin that's weird. I already have this in the `package.json`. It doesn't look like it works. Does it?

**Comment by robertoraggi** [comment]
@mkalygin is your app using create-react-app or babel to transpile the code? if this is the case try to add the following snippet to the package.json of your app

```
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

**Comment by harrycollin** [comment]
@mkalygin I used this exact snippet and it worked much better.

**Comment by mkalygin** [comment]
Ok, thanks @harrycollin @robertoraggi. I've fixed `package.json` in https://github.com/slaylines/harp.gl-react-example/commit/6dbdf5a84d2439be499f1a5e32478124f9cbc4f4. I'm closing this issue. Let me know if I can help in any way.
